### ISSUE TITLE
__FILE__ / __FUNCTION__ / __LINE__ support in metadata

### ISSUE THREAD

**Issue by ghost** [zschoche/mlog#2]
Hey there and thanks for this library, agreed that boost::log is pretty heavy and I'm also looking for a lighter alternative.

I was wondering if you had any plans to support the standard defined preprocessor macros in the `mlog::log_metadata` struct, such as `__FILE__`, `__FUNCTION__`, `__LINE__`, etc.  I find it much easier to look up in the source code where a problem is with these prepended to my log string, but they need to be captured at the macro level. 

For now I'm just going to define my own macros and build the string there, but I think it would be a nice feature (and relatively cheap) to be able to control that behavior from the `write_to_log` virtual method.

cheers,
Rich

**Comment by ibaun** [comment]
I believe this has gone in regression. With the current version of mlog, __FILE__ and __LINE__ are called in te templated write_message, which is called only in mlog.hpp.
